# Generated by Django 3.0.1 on 2020-08-30 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierprofile',
            name='suser',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='wuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='m_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='s_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='w_user',
        ),
        migrations.DeleteModel(
            name='ManagerProfile',
        ),
        migrations.DeleteModel(
            name='SupplierProfile',
        ),
        migrations.DeleteModel(
            name='WorkerProfile',
        ),
    ]
